-- Quick test: Check if username column exists
SELECT COLUMN_NAME, DATA_TYPE, IS_NULLABLE, COLUMN_KEY
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'crm_construction'
  AND TABLE_NAME = 'users'
ORDER BY ORDINAL_POSITION;
