CREATE TABLE IF NOT EXISTS annexures (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  description TEXT,
  clauses JSON,
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

ALTER TABLE quotations ADD COLUMN annexure_id INT NULL;
ALTER TABLE quotations ADD CONSTRAINT fk_quotation_annexure FOREIGN KEY (annexure_id) REFERENCES annexures(id);
